In [9]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
import lxmls.readers.sentiment_reader as srs
import lxmls.classifiers.naive_bayes as nb
src  = srs.SentimentCorpus("books")

2000
1600


In [116]:

src.train_X = np.array([[1,0,1,0],[1,1,0,0]])
src.train_y = np.array([[1],[0]])

In [117]:
import lxmls.classifiers.multinomial_naive_bayes as mnbb
mnbb = mnbb.MultinomialNaiveBayes()

params_nb_sc = mnbb.train(src.train_X, src.train_y)
print 'training finished'
y_pred_train = mnbb.test(src.train_X, params_nb_sc)
print 'testing finished'
acc_train = mnbb.evaluate(src.train_y, y_pred_train)

print("training accuracy %f" % acc_train)

y_pred_test = mnbb.test(src.test_X, src.test_y)
acc_test = mnbb.evaluate(src.test_y, params_nb_sc)
print("testing accuracy %f", acc_test)

2 4 2
(2, 2, 4)
[[[ 1.  0.  1.  0.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  0.  0.]
  [ 0.  0.  0.  0.]]]
(4, 2)
[[ 2.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 0.  1.]]
[[ 0.66666667  0.33333333]
 [ 0.5         0.5       ]
 [ 0.5         0.5       ]
 [ 0.          1.        ]]
training finished
testing finished
training accuracy 0.500000


ValueError: shapes (6,13990) and (6,1) not aligned: 13990 (dim 1) != 6 (dim 0)

In [63]:
x = np.array([range(10),range(10)])
y = x.copy()

z = np.array([x,y,x])
print z.shape

(3, 2, 10)


In [95]:
data = np.arange(40)
data.shape = (4,10)
print data
print data[data[:,0] < 5, 1]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
[1]


In [87]:
from __future__ import division
x = np.arange(10).reshape(5,2)
y = (np.arange(5) + 1).reshape(5,1)
z = x / y
print x, y, z

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] [[1]
 [2]
 [3]
 [4]
 [5]] [[ 0.          1.        ]
 [ 1.          1.5       ]
 [ 1.33333333  1.66666667]
 [ 1.5         1.75      ]
 [ 1.6         1.8       ]]


[autoreload of lxmls.classifiers.multinomial_naive_bayes failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/IPython/extensions/autoreload.py", line 247, in check
    superreload(m, reload, self.old_objects)
  File "/Users/ondrejplatek/code/lxmls-toolkit/lxmls/classifiers/multinomial_naive_bayes.py", line 35
    norms = np.sum(words_count_labels, axis=1)
        ^
SyntaxError: invalid syntax
]
