In [14]:
import numpy as np
import lxmls.readers.sentiment_reader as srs
scr = srs.SentimentCorpus("books")
train_x = scr.train_X.T
train_y = scr.train_y[:, 0]
test_x = scr.test_X.T
test_y = scr.test_y[:, 0]

2000
1600


In [7]:
x = test_x
W1, b1 = mlp.params[:2]
z1 = np.dot(W1, x) + b1
tilde_z1 = 1 / (1+np.exp(-z1))

NameError: name 'mlp' is not defined

In [13]:
import theano
import theano.tensor as T
_x = T.matrix('x')
_W1 = theano.shared(value=W1, name='W1', borrow=True)
_b1 = theano.shared(value=b1, name='b1', borrow=True, broadcastable=(False, True))

NameError: name 'W1' is not defined

In [15]:
_z1 = T.dot(_W1, _x) + _b1
_z1.name = 'z1'
_tilde_z1 = T.nnet.sigmoid(_z1)
_tilde_z1.name = 'tilde_z1'

theano.printing.debugprint(_tilde_z1)

NameError: name '_W1' is not defined

In [16]:
layer1 = theano.function([_x], _tilde_z1)

NameError: name '_tilde_z1' is not defined

Theano tutorial
========

Start here: http://deeplearning.net/software/theano/tutorial/adding.html

In [24]:
import theano.tensor as T
from theano import function
x = T.dscalar('x')
y = T.dscalar('y')
print x, type(x)
z = x + y
f = function([x, y], z)
from theano import pp
print pp(z), pp(x), pp(y)

x <class 'theano.tensor.var.TensorVariable'>
(x + y) x y


In [27]:
print f(2,3)
print z.eval({x:2, y:3})

5.0
5.0


In [33]:
import numpy
x = T.dmatrix('x')
y = T.dmatrix('y')
z = x + y
f = function([x,y], z)
print f([[1,2], [3,4]], [[10, 20], [30,40]])
print f(numpy.array([[1,2], [3,4]]), numpy.array([[10, 20], [30,40]]))

[[ 11.  22.]
 [ 33.  44.]]
[[ 11.  22.]
 [ 33.  44.]]


In [39]:
x = T.dmatrix('x')
s = 1 /(1+T.exp(-x))
logistic = function([x], s)
x_ = [[0,1], [-1, -2]]
print logistic(x_)
s2 = (1 + T.tanh(x/2))
tanh = function([x], s2)
print tanh(x_) / 2.0

[[ 0.5         0.73105858]
 [ 0.26894142  0.11920292]]
[[ 0.5         0.73105858]
 [ 0.26894142  0.11920292]]


In [50]:
a, b = T.dmatrices('a', 'b')
diff = a - b 
abs_diff = abs(diff)
diff_squared = diff**2
print pp(abs_diff)
f = function([a,b], [diff, abs_diff, diff_squared])
print f([[1, 1], [1, 1]], [[0, 1], [2, 3]])
print f(x_, x_)

|(a - b)|
[array([[ 1.,  0.],
       [-1., -2.]]), array([[ 1.,  0.],
       [ 1.,  2.]]), array([[ 1.,  0.],
       [ 1.,  4.]])]
[array([[ 0.,  0.],
       [ 0.,  0.]]), array([[ 0.,  0.],
       [ 0.,  0.]]), array([[ 0.,  0.],
       [ 0.,  0.]])]


In [58]:
from theano import shared
state = shared(0)
inc = T.iscalar('inc')
accumulator = function([inc], state, updates=[(state, state + inc)])
print state.get_value()
print accumulator(1)
print state.get_value()
print accumulator(300)
print state.get_value()
state.set_value(-1)
print state.get_value()
print accumulator(3)
print state.get_value()
decrementor = function([inc], state, updates=[(state, state-inc)])
print decrementor(6)
print state.get_value()


0
0
1
1
301
-1
-1
2
2
-4
